services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: flask-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "4000"
    networks:
      - default
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "4000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    expose:
      - "80"
      - "443"
#use this instead of "expose" if not using my custom NginxRouter service
#    ports:
#      - "80:80"  # Exposes port 80 for web traffic
#      - "443:443" # Expose ssl port for https
    depends_on:
      - server  # Ensures Flask is up before Nginx
    environment:
      - URL=${URL}
    volumes:
      - ./cert.pem:/etc/nginx/cert.pem:ro #https certificate / private key
      - ./key.pem:/etc/nginx/key.pem:ro #public key
      - ./client/build:/etc/nginx/html:ro #static webpage
    networks:
      - web-router
      - default

networks:
  web-router:
    external: true